import {it,expect,vi,afterEach} from 'vitest';import {mkdtempSync,rmSync,writeFileSync} from 'node:fs';import path from 'node:path';import {tmpdir} from 'node:os';import {testProfile,testBuyerProfile} from './helpers.js';import {SetupPublicError} from '../src/product-setup-public.js';import {WeixinError} from '../src/weixin/types.js';
const h=vi.hoisted(()=>({setup:vi.fn(),open:vi.fn(),close:vi.fn(async()=>{}),dir:'',profile:undefined as import("../src/config/profile.js").AgentProfile | undefined}));
vi.mock('../src/product-setup-public.js',async imp=>({...await imp<typeof import('../src/product-setup-public.js')>(),runMerchantSetupPublic:h.setup}));
vi.mock('../src/product-init.js',async imp=>({...await imp<typeof import('../src/product-init.js')>(),loadMerchantCredentials:()=>{}}));
vi.mock('../src/agent/kernel-builder.js',async imp=>({...await imp<typeof import('../src/agent/kernel-builder.js')>(),buildClient:()=>({}),buildChatKernel:async()=>({close:h.close}),defaultChatProfile:()=>h.profile}));
vi.mock('../src/weixin/channel.js',()=>({WeixinChannel:{open:h.open}}));
vi.mock('../src/operator/store.js',async imp=>({...await imp<typeof import('../src/operator/store.js')>(),FileOperatorEventStore:class{constructor(dir:string){h.dir=dir;}}}));
vi.mock('../src/operator/controller.js',async imp=>({...await imp<typeof import('../src/operator/controller.js')>(),OperatorController:class{async start(){}}}));
vi.mock('../src/operator/runner.js',async imp=>({...await imp<typeof import('../src/operator/runner.js')>(),DeterministicNegotiationRunner:class{}}));
vi.mock('../src/operator/tui.js',()=>({runTui:async()=>0}));
import {main,resolveServeDataDir} from '../src/cli.js';import {cmdWeixin} from '../src/weixin/cli-weixin.js';
const dirs:string[]=[];const sigint=new Set(process.listeners('SIGINT')),sigterm=new Set(process.listeners('SIGTERM'));
afterEach(()=>{vi.restoreAllMocks();vi.clearAllMocks();for(const d of dirs.splice(0))rmSync(d,{recursive:true,force:true});for(const f of process.listeners('SIGINT'))if(!sigint.has(f))process.removeListener('SIGINT',f);for(const f of process.listeners('SIGTERM'))if(!sigterm.has(f))process.removeListener('SIGTERM',f);});
function fixture(p:import("../src/config/profile.js").AgentProfile){const dir=mkdtempSync(path.join(tmpdir(),'a359-cli-'));dirs.push(dir);const file=path.join(dir,'profile.json');writeFileSync(file,JSON.stringify(p));return {dir,file};}
it('2-27 merchant up maps same SetupPublicError to CONFIG before any process start',async()=>{const f=fixture(testProfile());h.setup.mockRejectedValue(new SetupPublicError('CONFIG','A359 fake setup error'));vi.spyOn(process.stderr,'write').mockImplementation(()=>true);await expect(main(['merchant','up','--profile',f.file,'--domain','a359.invalid'])).resolves.toBe(2);expect(h.setup).toHaveBeenCalledOnce();});
it('2-27 unexpected runtime failure is not mislabeled as configuration',async()=>{const f=fixture(testProfile());h.setup.mockRejectedValue(new Error('A359 runtime failure'));await expect(main(['merchant','up','--profile',f.file,'--domain','a359.invalid'])).rejects.toThrow('runtime failure');});
for(const [code,expected] of [['network',10],['timeout',10],['session_stale',10],['qr_expired',10],['not_configured',2],['validation',2],['auth',3]] as const)it('2-28 actual startup error '+code+' maps exit '+expected+' and closes local kernel',async()=>{h.profile=testBuyerProfile();const f=fixture(h.profile);h.open.mockRejectedValue(new WeixinError(code,'A359 fake error'));vi.spyOn(process.stderr,'write').mockImplementation(()=>true);expect(await cmdWeixin({dataDir:path.join(f.dir,'state'),relogin:false,a2a:false,qrScale:1,noQr:true})).toBe(expected);expect(h.close).toHaveBeenCalledOnce();});
it('3-50 TUI honors same profile state directory as serve',async()=>{const f=fixture(testProfile({agent_id:'merchant:a359',merchant_runtime:{data_dir:'/synthetic/a359-profile-state'} as never}));expect(await main(['tui','--profile',f.file])).toBe(0);expect(h.dir).toBe(resolveServeDataDir(undefined,'merchant:a359','/synthetic/a359-profile-state'));});
it('3-50 explicit TUI data directory remains authoritative',async()=>{const f=fixture(testProfile());const requested=path.join(f.dir,'explicit');expect(await main(['tui','--profile',f.file,'--data-dir',requested])).toBe(0);expect(h.dir).toBe(requested);});
it('3-50 TUI default identity directory matches serve normalization without creating or migrating it',async()=>{const p=testProfile({agent_id:'merchant:a359@namespace'});const f=fixture(p);expect(await main(['tui','--profile',f.file])).toBe(0);expect(h.dir).toBe(resolveServeDataDir(undefined,p.agent_id));});

it('3-50 unsafe identity is refused by TUI just as serve, without directory creation',async()=>{const f=fixture(testProfile({agent_id:'merchant:a359/unsafe'}));await expect(main(['tui','--profile',f.file])).rejects.toThrow(/agent_id.*safe/);});
