import {Readable} from 'node:stream';
import {afterEach,expect,it,vi} from 'vitest';
vi.mock('../src/auth/merchant-sessions.js',async imp=>({...await imp<typeof import('../src/auth/merchant-sessions.js')>(),readAdminCredentials:()=>({principal_id:'a367-fixture',merchant_id:'a367-fixture',password_hash:'synthetic-only'}),verifyAdminPassword:(pw:string)=>pw==='a367-correct'}));
import {createMerchantHttpHandler} from '../src/mcp/merchant-server.js';
const closers:(()=>Promise<void>)[]=[];
afterEach(async()=>{vi.restoreAllMocks();for(const close of closers.splice(0))await close();});
function fixture(){let now=1_700_000_000_000;vi.spyOn(Date,'now').mockImplementation(()=>now);const sessions={createSession:vi.fn(()=>({sessionId:'synthetic-session'}))};const handle=createMerchantHttpHandler({service:{},admin:{adminDir:'/never-read-a367',sessions,surface:{}}} as never);closers.push(handle.close);return {sessions,advance:()=>{now+=300_001;},login:async(password:string,ip='192.0.2.1',xff='')=>new Promise<{status:number;headers:Record<string,string>}>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('login fixture timeout')),2000);const req=Readable.from([Buffer.from(new URLSearchParams({password}).toString())]);Object.assign(req,{url:'/admin/login',method:'POST',headers:{'content-type':'application/x-www-form-urlencoded','x-forwarded-for':xff},socket:{remoteAddress:ip}});let status=0;let headers:Record<string,string>={};handle.handler(req as never,{headersSent:false,writeHead:(code:number,h:Record<string,string>)=>{status=code;headers=h;},end:()=>{clearTimeout(timer);resolve({status,headers});}} as never);})};}
it('2-16 expiry starts a new failure window and correct password clears it',async()=>{const h=fixture();for(let n=0;n<10;n++)expect((await h.login('wrong')).status).toBe(200);expect((await h.login('wrong')).status).toBe(429);h.advance();for(let n=0;n<10;n++)expect((await h.login('wrong')).status).toBe(200);expect((await h.login('wrong')).status).toBe(429);h.advance();expect((await h.login('a367-correct')).status).toBe(303);for(let n=0;n<9;n++)expect((await h.login('wrong')).status).toBe(200);expect(h.sessions.createSession).toHaveBeenCalledTimes(1);});
it('2-16 forged XFF does not rotate a socket bucket or bypass an active block',async()=>{const h=fixture();for(let n=0;n<10;n++)expect((await h.login('wrong','192.0.2.1',`198.51.100.${n}`)).status).toBe(200);expect((await h.login('a367-correct','192.0.2.1','203.0.113.99')).status).toBe(429);expect((await h.login('wrong','192.0.2.2','203.0.113.99')).status).toBe(200);h.advance();expect((await h.login('a367-correct','192.0.2.1')).status).toBe(303);expect(h.sessions.createSession).toHaveBeenCalledTimes(1);});
