import fs from 'node:fs';
import cp from 'node:child_process';
import {syncBuiltinESMExports} from 'node:module';
import path from 'node:path';
import {tmpdir} from 'node:os';
import {pathToFileURL} from 'node:url';
import {build} from 'esbuild';
import {afterAll,afterEach,beforeAll,expect,it,vi} from 'vitest';
import {runInit} from '../src/supervisor/init.js';
const dirs:string[]=[];const children:cp.ChildProcess[]=[];const childErrors:string[]=[];let bundle:string;let mod:{__a367Acquire:(dir:string)=>()=>void;runUp:(dir:string)=>Promise<unknown>};
function temp(){const d=fs.mkdtempSync(path.join(tmpdir(),'a367-up-'));dirs.push(d);return d;}
beforeAll(async()=>{const d=temp();const source=fs.readFileSync('src/supervisor/manage.ts','utf8')+'\nexport { acquireUpLock as __a367Acquire };\n';const output=path.join(d,'manage.mjs');await build({stdin:{contents:source,resolveDir:path.resolve('src/supervisor'),sourcefile:'manage.ts',loader:'ts'},outfile:output,bundle:true,platform:'node',format:'esm',banner:{js:'import { createRequire } from "node:module"; const require = createRequire(import.meta.url);'}});bundle=pathToFileURL(output).href;mod=await import(/* @vite-ignore */bundle);});
afterEach(async()=>{vi.restoreAllMocks();vi.unstubAllGlobals();vi.unstubAllEnvs();syncBuiltinESMExports();for(const c of children.splice(0)){if(c.exitCode===null&&c.signalCode===null){c.kill('SIGTERM');await Promise.race([new Promise(r=>c.once('exit',r)),new Promise(r=>setTimeout(r,300))]);if(c.exitCode===null&&c.signalCode===null)c.kill('SIGKILL');}}});
afterAll(()=>{if(process.env.A367_RAW_DIR){fs.mkdirSync(process.env.A367_RAW_DIR,{recursive:true});fs.writeFileSync(path.join(process.env.A367_RAW_DIR,'child-stderr.txt'),childErrors.join('\n'));for(const d of dirs){const e=path.join(d,'events');if(fs.existsSync(e))fs.copyFileSync(e,path.join(process.env.A367_RAW_DIR,path.basename(d)+'.jsonl'));}}for(const d of dirs)fs.rmSync(d,{recursive:true,force:true});});
it.each(['EPERM','EINVAL','EIO',undefined])('3-47 unknown PID probe %s retains lock',code=>{const d=temp(),p=path.join(d,'up.lock');fs.writeFileSync(p,'123456\n');vi.spyOn(process,'kill').mockImplementation(()=>{throw Object.assign(new Error('synthetic probe'),{code});});expect(()=>mod.__a367Acquire(d)).toThrow();expect(fs.readFileSync(p,'utf8')).toBe('123456\n');});
it.each(['0','-1','123junk','1e3','', '9007199254740993'])('3-47 malformed PID %j retains lock',text=>{const d=temp(),p=path.join(d,'up.lock');fs.writeFileSync(p,text);const probe=vi.spyOn(process,'kill');expect(()=>mod.__a367Acquire(d)).toThrow();expect(fs.readFileSync(p,'utf8')).toBe(text);expect(probe).not.toHaveBeenCalled();});
it('3-47 only ESRCH recovers strict legacy PID and release removes only its own lock',()=>{const d=temp(),p=path.join(d,'up.lock');fs.writeFileSync(p,'123456\n');vi.spyOn(process,'kill').mockImplementation(()=>{throw Object.assign(new Error('dead'),{code:'ESRCH'});});const release=mod.__a367Acquire(d);expect(fs.existsSync(p)).toBe(true);release();expect(fs.existsSync(p)).toBe(false);release();});
it('3-47 live owner remains untouched',()=>{const d=temp(),p=path.join(d,'up.lock');fs.writeFileSync(p,String(process.pid));expect(()=>mod.__a367Acquire(d)).toThrow();expect(fs.readFileSync(p,'utf8')).toBe(String(process.pid));});
it('3-47 stale release cannot delete a replaced nonce owner',()=>{const d=temp(),p=path.join(d,'up.lock');const release=mod.__a367Acquire(d);const replacement=JSON.stringify({pid:process.pid,nonce:'f'.repeat(32)});fs.writeFileSync(p,replacement);release();expect(fs.readFileSync(p,'utf8')).toBe(replacement);});
it('3-47 unknown guard is retained, never guessed stale',()=>{const d=temp(),p=path.join(d,'up.lock.guard');fs.writeFileSync(p,'unknown guard');expect(()=>mod.__a367Acquire(d)).toThrow();expect(fs.readFileSync(p,'utf8')).toBe('unknown guard');expect(fs.existsSync(path.join(d,'up.lock'))).toBe(false);});
it('3-47 metadata write failure leaves barrier and closes owned descriptors',()=>{const d=temp();const real=fs.writeSync;const close=vi.spyOn(fs,'closeSync');vi.spyOn(fs,'writeSync').mockImplementation(((fd:number,data:unknown,...rest:unknown[])=>{if(String(data).includes('"pid"'))throw Object.assign(new Error('metadata fault'),{code:'EIO'});return (real as any)(fd,data,...rest);}) as never);syncBuiltinESMExports();expect(()=>mod.__a367Acquire(d)).toThrow('metadata fault');expect(fs.existsSync(path.join(d,'up.lock'))).toBe(true);expect(close).toHaveBeenCalled();});
it('3-47 public runUp keeps EPERM lock and never spawns business',async()=>{const d=temp(),shopping=path.join(d,'shopping-src');fs.mkdirSync(path.join(shopping,'shopping_cli'),{recursive:true});const instance=path.join(d,'instance');await runInit({dir:instance,shoppingCliSrc:shopping,fake:true});vi.stubEnv('SHOPPING_AGENT_TOKEN','a367-fake-agent');vi.stubEnv('SHOPPING_BUYER_TOKEN','a367-fake-buyer');vi.stubGlobal('fetch',vi.fn().mockRejectedValue(new Error('network forbidden')));const p=path.join(instance,'run','up.lock');fs.writeFileSync(p,'123456');vi.spyOn(process,'kill').mockImplementation(()=>{throw Object.assign(new Error('permission'),{code:'EPERM'});});const spawn=vi.spyOn(cp,'spawn').mockImplementation(()=>{throw Error('business spawn forbidden');});syncBuiltinESMExports();await expect(mod.runUp(instance)).rejects.toThrow();expect(fs.readFileSync(p,'utf8')).toBe('123456');expect(spawn).not.toHaveBeenCalled();});
function logs(file:string){if(!fs.existsSync(file))return [];return fs.readFileSync(file,'utf8').split('\n').filter(Boolean).flatMap(x=>{try{return [JSON.parse(x)];}catch{return [];}});}
async function until(test:()=>boolean){const end=Date.now()+4000;while(!test()&&Date.now()<end)await new Promise(r=>setTimeout(r,5));expect(test(),childErrors.join("\n")).toBe(true);}
function child(options:Record<string,unknown>){const c=cp.spawn(process.execPath,['tests/fixtures/a367-up-lock-child.mjs',JSON.stringify({...options,bundle})],{stdio:['ignore','pipe','pipe']});children.push(c);c.stderr?.on('data',b=>childErrors.push(String(b)));const done=new Promise<number|null>(resolve=>c.once('exit',resolve));return {c,done};}
it.each(['acquire','release'])('3-47 real two-child %s mutation window is guarded',async mode=>{const d=temp(),lock=path.join(d,'up.lock'),events=path.join(d,'events'),release=path.join(d,'release'),finish=path.join(d,'finish');if(mode==='acquire')fs.writeFileSync(lock,'123456');const r=child({dir:d,lock,events,release,finish,actor:'R',pause:true,mode});await until(()=>logs(events).some(x=>x.actor==='R'&&x.event==='before-unlink'));const a=child({dir:d,lock,events,release,finish,actor:'A',pause:false,mode:'hold'});await until(()=>logs(events).some(x=>x.actor==='A'&&(x.event==='owned'||x.event==='blocked')));const blocked=logs(events).some(x=>x.actor==='A'&&x.event==='blocked');fs.writeFileSync(release,'go');await until(()=>logs(events).some(x=>x.actor==='R'&&(x.event==='owned'||x.event==='done')));fs.writeFileSync(finish,'go');await Promise.all([r.done,a.done]);expect(blocked,JSON.stringify(logs(events))).toBe(true);expect(r.c.exitCode).toBe(0);});

it('3-47 guard metadata failure retains unknown guard and closes its fd',()=>{const d=temp();const close=vi.spyOn(fs,'closeSync');vi.spyOn(fs,'writeSync').mockImplementation(()=>{throw Error('guard metadata fault');});syncBuiltinESMExports();expect(()=>mod.__a367Acquire(d)).toThrow('guard metadata fault');expect(fs.existsSync(path.join(d,'up.lock.guard'))).toBe(true);expect(close).toHaveBeenCalledTimes(1);expect(fs.existsSync(path.join(d,'up.lock'))).toBe(false);});
it('3-47 release guard failure preserves main barrier without masking caller result',()=>{const d=temp(),p=path.join(d,'up.lock');const release=mod.__a367Acquire(d);fs.writeFileSync(p+'.guard','unknown guard');const action=()=>{try{return 'business-result';}finally{release();}};expect(action()).toBe('business-result');expect(fs.existsSync(p)).toBe(true);expect(fs.readFileSync(p+'.guard','utf8')).toBe('unknown guard');const other=temp();const stop=mod.__a367Acquire(other);fs.writeFileSync(path.join(other,'up.lock.guard'),'unknown');const original=new Error('original business fault');expect(()=>{try{throw original;}finally{stop();}}).toThrow(original);});
