import {it,expect,vi} from 'vitest';import {Readable} from 'node:stream';
import {createMerchantHttpHandler,startMerchantMcpServer} from '../src/mcp/merchant-server.js';import {StaticBearerTokenVerifier} from '../src/mcp/merchant-auth.js';import {A2ATaskPoller} from '../src/a2a/task/poller.js';
async function invoke(localAddress:string|undefined,auth?:StaticBearerTokenVerifier,bearer?:string){const h=createMerchantHttpHandler({service:{} as never,...(auth?{auth}:{} )});const req=Readable.from([]);Object.assign(req,{url:'/mcp',method:'PATCH',headers:{host:'localhost','x-forwarded-for':'127.0.0.1',...(bearer?{authorization:bearer}:{})},socket:{localAddress,remoteAddress:'127.0.0.1'}});try{return await new Promise<number>((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('fixture timeout')),1000);h.handler(req as never,{writeHead:(status:number)=>{(req as any).status=status;},end:()=>{clearTimeout(timer);resolve((req as any).status);},headersSent:false} as never);});}finally{await h.close();}}
it.each(['127.0.0.1','::1','::ffff:127.0.0.1','::ffff:7f00:1','0:0:0:0:0:0:0:1'])('A387 trusted socket %s reaches ordinary method policy',async a=>{expect(await invoke(a)).toBe(405);});
it.each([undefined,'0.0.0.0','::','192.0.2.9','10.0.0.1','localhost'])('A387 socket %s rejects before MCP even with forged loopback Host/XFF',async a=>{expect(await invoke(a)).toBe(403);});
it('A387 configured authentication remains mandatory regardless of socket and Host',async()=>{const auth=new StaticBearerTokenVerifier('synthetic-token');expect(await invoke('192.0.2.9',auth)).toBe(401);expect(await invoke('192.0.2.9',auth,'Bearer synthetic-token')).toBe(405);});
it.each(['0.0.0.0','::','192.0.2.9'])('A387 listener %s rejects no-auth before service construction or listen',async host=>{let inspected=0;const service=new Proxy({},{get(){inspected++;throw Error('service must not be touched');}});await expect(startMerchantMcpServer({service:service as never,host,port:0})).rejects.toThrow(/fail-closed/);expect(inspected).toBe(0);});
it('A387 poll lifecycle is per invocation; business may observe a later independent turn',async()=>{const values=['completed','working','completed'] as const;let n=0;const client={getTask:async()=>({id:'task',status:{state:values[n++]??'completed'}})};const p=new A2ATaskPoller({client,taskId:'task',sleep:async()=>{},now:()=>1000});expect((await p.poll()).status).toBe('completed');expect((await p.poll()).status).toBe('completed');expect(n).toBe(3);});
it.each(['127.0.0.1','::1'])('A387 actual %s local listener remains usable without auth',async host=>{const h=await startMerchantMcpServer({service:{} as never,host,port:0});try{const r=await fetch(h.url,{method:'PATCH'});expect(r.status).toBe(405);await r.text();}finally{await h.close();}});
it('A387 authenticated default wildcard listener retains bearer checks',async()=>{const h=await startMerchantMcpServer({service:{} as never,port:0,auth:new StaticBearerTokenVerifier('synthetic-token')});try{expect(h.host).toBe('0.0.0.0');expect((await fetch(h.url,{method:'PATCH'})).status).toBe(401);const r=await fetch(h.url,{method:'PATCH',headers:{authorization:'Bearer synthetic-token'}});expect(r.status).toBe(405);await r.text();}finally{await h.close();}});
