/**
 * `kiwi init` — create a self-contained managed-local instance.
 *
 * Creates exactly these known files/directories and nothing else:
 *   kiwi.stack.json (0600)   stack config (no secrets)
 *   profiles/merchant.yaml   merchant agent profile (env-var names only)
 *   profiles/buyer.yaml      buyer agent profile (env-var names only)
 *   data/                    gateway database location (created on demand)
 *   logs/                    per-process logs
 *   run/ (0700)              private manifest/exit-state dir
 *
 * Fail closed: an instance that already contains Kiwi state (config file or
 * run dir) is rejected, and every file is created with O_EXCL so user files
 * are never overwritten.
 */

import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import {
  assertSafeInstanceDir,
  detectShoppingCliSrc,
  instancePaths,
  newInstanceId,
  pickFreePort,
  STACK_VERSION,
  StackConfigError,
  type StackConfig,
} from "./stack-config.js";
import { packageRoot } from "../contracts/schemas.js";
import { PROTOCOL_VERSION } from "../negotiation/types.js";

export interface InitOptions {
  dir: string;
  shoppingCliSrc?: string;
  /** Demo/test mode: deterministic fake models, no model API key needed. */
  fake?: boolean;
}

export interface InitResult {
  dir: string;
  config_path: string;
  instance_id: string;
  base_url: string;
  mode: "managed-local";
  fake: boolean;
  created: string[];
}

/** Write a file only if it does not exist; never overwrite user files. */
function writeExclusive(file: string, content: string, mode: number): void {
  try {
    writeFileSync(file, content, { encoding: "utf-8", flag: "wx", mode });
  } catch (err) {
    if ((err as { code?: string }).code === "EEXIST") {
      throw new StackConfigError(`refusing to overwrite existing file: ${file}`);
    }
    throw err;
  }
}

function merchantProfile(baseUrl: string, fake: boolean): string {
  const model = fake
    ? "  provider: fake\n  model: fake-merchant-model\n"
    : "  provider: openai\n  model: gpt-4o-mini\n  api_key_env: MODEL_API_KEY\n";
  return `# Merchant agent profile — generated by kiwi init. Secrets stay in env vars.
runtime_version: 0.5.0
protocol_version: ${PROTOCOL_VERSION}
agent_id: merchant-agent:merchant-001
role: merchant
owner_id: merchant-001
commerce:
  base_url: ${baseUrl}
  token_env: SHOPPING_AGENT_TOKEN
  backend: local_marketplace
model:
${model}runtime:
  mode: foreground
  poll_interval_seconds: 5
  turn_timeout_seconds: 90
  max_model_steps: 4
  max_retries: 2
merchant_policy:
  min_unit_price_private: 80.00
  max_auto_discount_percent: 10
  inventory_source: marketplace
  quote_ttl_seconds: 300
  auto_negotiate: true
  human_review_on:
    - below_floor
    - exceptional_warranty
    - suspicious_content
`;
}

function buyerProfile(baseUrl: string, fake: boolean): string {
  const model = fake
    ? "  provider: fake\n  model: fake-buyer-model\n"
    : "  provider: openai\n  model: gpt-4o-mini\n  api_key_env: MODEL_API_KEY\n";
  return `# Buyer agent profile — generated by kiwi init. Secrets stay in env vars.
runtime_version: 0.5.0
protocol_version: ${PROTOCOL_VERSION}
agent_id: buyer-agent:buyer-001
role: buyer
owner_id: buyer-001
commerce:
  base_url: ${baseUrl}
  token_env: SHOPPING_BUYER_TOKEN
  backend: local_marketplace
model:
${model}runtime:
  mode: foreground
  poll_interval_seconds: 5
  turn_timeout_seconds: 90
  max_model_steps: 4
  max_retries: 2
buyer_policy:
  target_skus:
    - sku-001
  quantity: 2
  max_total_price_private: 200.00
  acceptable_eta_latest: "2099-12-31T23:59:59+08:00"
  required_after_sales_terms:
    - policy:return-7d
  auto_negotiate: true
  human_review_on:
    - budget_exceeded
    - ambiguous_after_sales
`;
}

export async function runInit(options: InitOptions): Promise<InitResult> {
  const dir = assertSafeInstanceDir(options.dir);
  const paths = instancePaths(dir);

  // Fail closed: any existing Kiwi state means this is (or was) an instance.
  if (existsSync(paths.config) || existsSync(paths.run)) {
    throw new StackConfigError(
      `${dir} already contains Kiwi state (${path.basename(paths.config)} or run/); refusing to re-init`,
    );
  }

  const fake = options.fake === true;

  // Resolve the shopping-cli source for the managed gateway BEFORE creating
  // anything.
  const src =
    options.shoppingCliSrc !== undefined
      ? path.resolve(options.shoppingCliSrc)
      : detectShoppingCliSrc(packageRoot());
  if (src === undefined || !existsSync(path.join(src, "shopping_cli"))) {
    throw new StackConfigError(
      "shopping-cli source not found: pass --shopping-cli-src <path> (expected a repo containing shopping_cli/)",
    );
  }
  const venvPython = path.join(src, ".venv", "bin", "python");
  const useVenv = existsSync(venvPython);

  const port = await pickFreePort();
  const baseUrl = `http://127.0.0.1:${port}`;
  const instanceId = newInstanceId();
  const createdAt = new Date().toISOString();
  const dbPath = path.join(paths.data, "shopping.sqlite");

  const config: StackConfig = {
    stack_version: STACK_VERSION,
    instance_id: instanceId,
    mode: "managed-local",
    created_at: createdAt,
    gateway: {
      base_url: baseUrl,
      command: [
        useVenv ? venvPython : "python3",
        "-m",
        "shopping_cli.api.server",
        "--db",
        dbPath,
        "--host",
        "127.0.0.1",
        "--port",
        String(port),
      ],
      env: useVenv ? {} : { PYTHONPATH: src },
    },
    agents: {
      merchant: { enabled: true, profile: "profiles/merchant.yaml" },
      buyer: { enabled: true, profile: "profiles/buyer.yaml" },
    },
  };

  const files: [string, string][] = [
    [paths.config, `${JSON.stringify(config, null, 2)}\n`],
    [path.join(paths.profiles, "merchant.yaml"), merchantProfile(baseUrl, fake)],
    [path.join(paths.profiles, "buyer.yaml"), buyerProfile(baseUrl, fake)],
  ];
  const dirs = [paths.profiles, paths.data, paths.logs, paths.run];

  // Preflight EVERY known target before creating anything: no partial Kiwi
  // state may be left behind when a user file is in the way.
  for (const [file] of files) {
    if (existsSync(file)) {
      throw new StackConfigError(`refusing to overwrite existing file: ${file}`);
    }
  }

  // Transactional create: on any failure remove only what THIS invocation
  // created (files it wrote; directories it made and only while empty).
  const createdFiles: string[] = [];
  const createdDirs: string[] = [];
  try {
    for (const d of dirs) {
      if (!existsSync(d)) {
        createdDirs.push(d);
      }
      // run/ holds manifests (pids, tokens-in-path); data/ holds the
      // shopping SQLite database — both stay owner-only. profiles/ and
      // logs/ carry 0600 files, so the dirs stay conventionally listable.
      mkdirSync(d, { recursive: true, mode: d === paths.run || d === paths.data ? 0o700 : 0o755 });
    }
    for (const [file, content] of files) {
      writeExclusive(file, content, 0o600);
      createdFiles.push(file);
    }
  } catch (err) {
    for (const file of createdFiles.reverse()) {
      rmSync(file, { force: true });
    }
    for (const d of createdDirs.reverse()) {
      // rmdir (non-recursive) only succeeds on empty dirs we just made;
      // anything containing user content is left untouched.
      try {
        rmSync(d, { recursive: false });
      } catch {
        // not empty or already gone: leave it
      }
    }
    throw err;
  }

  return {
    dir,
    config_path: paths.config,
    instance_id: instanceId,
    base_url: baseUrl,
    mode: "managed-local",
    fake,
    created: createdFiles,
  };
}
