#!/usr/bin/env node
/**
 * Copyright 2026 harrylabsj
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * `kiwi buyer` 命令面（product-strategy rev1.1 §2.2/§19 D4）。
 *
 * Buyer 只需要 Kiwi，不感知 shopping-cli / kiwi-catalog（§2.2）：
 * - init：生成 buyer profile（不需要 shopping-cli；agent_id 即 buyer 身份）；
 * - search：Product-first 搜索（复用 KiwiCatalogSource.searchListings——
 *   M3 链路；输出 authority/requires_direct_confirmation 标注，不伪装权威价）；
 * - tasks：读本地 BuyerTaskStore 任务列表（AgentKernel data dir）。
 */

import { randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";
import { hostname } from "node:os";
import { DatabaseSync } from "node:sqlite";
import path from "node:path";
import { stringify as stringifyYaml } from "yaml";
import { agentDataDir } from "./agent/agent-db.js";
import { RUNTIME_VERSION } from "./config/profile.js";
import { writeDefaultProfile } from "./product-cli.js";
import { PROTOCOL_VERSION } from "./negotiation/types.js";
import { KiwiCatalogSource } from "./discovery/catalog-source/index.js";

// ── buyer init ─────────────────────────────────────────────────────────────

/** 缺省 buyer 身份：buyer-<hostname>-<短随机>（同机多次 init 稳定可复用）。 */
function defaultBuyerAgentId(): string {
  const random = randomBytes(3).toString("hex");
  const host = hostname().replace(/[^a-z0-9-]/gi, "-").toLowerCase() || "local";
  return `buyer-${host}-${random}`;
}

export interface BuyerInitOptions {
  agentId: string;
  ownerId?: string;
  /** legacy marketplace 磋商 base URL（buyer 经 catalog/A2A 时非必需）。 */
  shoppingCliUrl?: string;
  autoNegotiate?: boolean;
  outputPath?: string;
  /**
   * 默认 profile 写入路径（裸 `kiwi` 读取；缺省 DEFAULT_PROFILE_PATH）。
   * 测试注入隔离用——init 测试不得污染真实 `~/.kiwi/kiwi.yaml`。
   */
  defaultProfilePath?: string;
  force?: boolean;
  modelProvider?: string;
  modelName?: string;
  apiKeyEnv?: string;
}

export interface BuyerInitReport {
  ok: boolean;
  profile_path: string;
  agent_id: string;
  detail: string;
  warnings: string[];
}

export function buyerInit(options: BuyerInitOptions): BuyerInitReport {
  const warnings: string[] = [];
  // 身份缺省自动生成（普通用户不需要想 agent-id；显式指定用于跨设备延续身份）
  const agentId = options.agentId.trim() !== "" ? options.agentId.trim() : defaultBuyerAgentId();
  const ownerId = options.ownerId?.trim() || agentId;
  const profile: Record<string, unknown> = {
    // 由 `kiwi buyer init` 生成（D4）。secret 永不入 profile（token_env 只写环境变量名）。
    runtime_version: RUNTIME_VERSION,
    protocol_version: PROTOCOL_VERSION,
    agent_id: agentId,
    role: "buyer",
    owner_id: ownerId,
    commerce: {
      base_url: options.shoppingCliUrl ?? "http://127.0.0.1:8765",
      token_env: "SHOPPING_BUYER_TOKEN",
      backend: "local_marketplace",
    },
    model: {
      provider: options.modelProvider ?? "deepseek",
      model: options.modelName ?? "deepseek-v4-flash",
      api_key_env: options.apiKeyEnv ?? "DEEPSEEK_API_KEY",
    },
    runtime: {
      mode: "once",
      poll_interval_seconds: 5,
      turn_timeout_seconds: 90,
      max_model_steps: 4,
      max_retries: 2,
    },
    buyer_policy: {
      target_skus: [],
      quantity: 1,
      max_total_price_private: 1_000_000,
      acceptable_eta_latest: "2099-12-31T23:59:59+08:00",
      required_after_sales_terms: [],
      auto_negotiate: options.autoNegotiate ?? true,
      human_review_on: [],
    },
  };

  const outputPath = options.outputPath ?? path.resolve("buyer.yaml");
  if (existsSync(outputPath) && !options.force) {
    return {
      ok: false,
      profile_path: outputPath,
      agent_id: agentId,
      detail: `已存在：${outputPath}（用 --force 覆盖）`,
      warnings,
    };
  }
  try {
    const yaml = `# Kiwi Buyer profile — generated by \`kiwi buyer init\` (${new Date().toISOString()})\n` +
      stringifyYaml(profile);
    writeFileSync(outputPath, yaml, { mode: 0o600 });
    // 同时写默认 profile：之后裸 `kiwi` 即按此 buyer 运行。
    writeDefaultProfile(yaml, options.defaultProfilePath);
  } catch (err) {
    return {
      ok: false,
      profile_path: outputPath,
      agent_id: agentId,
      detail: `写盘失败：${err instanceof Error ? err.message : String(err)}`,
      warnings,
    };
  }
  return { ok: true, profile_path: outputPath, agent_id: agentId, detail: "ok", warnings };
}

// ── buyer search（Product-first）───────────────────────────────────────────

export interface BuyerSearchOptions {
  query: string;
  catalogUrl: string;
  limit?: number;
  category?: string;
  region?: string;
  listingType?: "product" | "capability";
  fetchImpl?: typeof fetch;
}

export interface BuyerSearchHit {
  listing_id: string;
  listing_type: string;
  title: string;
  category: string;
  commercial_hints?: unknown;
  merchant: string;
  owner_agent_id: string;
  owner_verification: string;
  listing_freshness_state: string;
  authority: "discovery_projection";
  requires_direct_confirmation: true;
}

/** Product-first 搜索（M3 链路复用）。discovery projection，不伪装权威价。 */
export async function buyerSearch(options: BuyerSearchOptions): Promise<BuyerSearchHit[]> {
  const source = new KiwiCatalogSource({
    baseUrl: options.catalogUrl,
    ...(options.fetchImpl !== undefined ? { fetchImpl: options.fetchImpl } : {}),
  });
  const results = await source.searchListings({
    q: options.query,
    ...(options.category !== undefined ? { category: options.category } : {}),
    ...(options.region !== undefined ? { region: options.region } : {}),
    ...(options.listingType !== undefined ? { listing_type: options.listingType } : {}),
    ...(options.limit !== undefined ? { limit: options.limit } : {}),
  });
  return results.map((r) => ({
    listing_id: r.listing.listing_id,
    listing_type: r.listing.listing_type,
    title: r.listing.title,
    category: r.listing.category,
    ...(r.listing.commercial_hints !== undefined
      ? { commercial_hints: r.listing.commercial_hints }
      : {}),
    merchant: r.merchant.display_name,
    owner_agent_id: r.agent.catalog_agent_id,
    owner_verification: r.agent.verification_level,
    listing_freshness_state: r.listing.listing_freshness_state,
    authority: r.authority,
    requires_direct_confirmation: r.requires_direct_confirmation,
  }));
}

// ── buyer tasks ────────────────────────────────────────────────────────────

export interface BuyerTasksOptions {
  /** AgentKernel data dir（缺省 agentDataDir(agentId)）。 */
  dataDir?: string;
  agentId?: string;
}

export interface BuyerTaskSummary {
  task_id: string;
  status: string;
  goal_text: string;
  created_at: string;
  updated_at: string;
}

/** 读本地 BuyerTaskStore 任务列表（start 运行过才有数据；缺省报错）。 */
export async function buyerTasks(options: BuyerTasksOptions): Promise<BuyerTaskSummary[]> {
  const dataDir = options.dataDir ?? agentDataDir(options.agentId ?? "kiwi-assistant");
  const dbPath = path.join(dataDir, "state.sqlite");
  if (!existsSync(dbPath)) {
    throw new Error(
      `没有 Buyer 任务数据（${dbPath} 不存在）——先运行 \`kiwi buyer start\` 产生任务`,
    );
  }
  const db = new DatabaseSync(dbPath);
  try {
    const rows = db
      .prepare(
        "select task_id, status, goal_text, created_at, updated_at" +
          " from buyer_tasks order by updated_at desc limit 50",
      )
      .all() as Array<{
      task_id: string;
      status: string;
      goal_text: string;
      created_at: string;
      updated_at: string;
    }>;
    return rows.map((row) => ({
      task_id: row.task_id,
      status: row.status,
      goal_text: row.goal_text,
      created_at: row.created_at,
      updated_at: row.updated_at,
    }));
  } finally {
    db.close();
  }
}
